"""add patient_id to reports, make scan_id nullable

Revision ID: 98984bd1d846
Revises: eefdd96b5bbc
Create Date: 2026-09-12 22:19:23.847286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98984bd1d846'
down_revision = 'eefdd96b5bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.alter_column('scan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('scan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
